package ru.lexender.project.inbetween;

public enum Prompt {
    REGISTRATION_OK,
    USER_EXISTS,
    DISCONNECTED,
    CONNECTED,
    LOGGED_IN,
    INVALID_PASSWORD,
    USER_NOT_EXISTS,
    INVALID_AMOUNT,
    INVALID_ARGUMENT,
    INVALID_COMMAND,
    TRANSACTION_OK,
    UNEXPECTED_ERROR,
    ADD_ARGUMENT,
    STORAGE_UNAVAILABLE

}
