package ru.lexender.project.inbetween;

public enum Prompt {
    DISCONNECTED,
    CONNECTED,
    INVALID_AMOUNT,
    INVALID_ARGUMENT,
    INVALID_COMMAND,
    TRANSACTION_OK,
    UNEXPECTED_ERROR,
    ADD_ARGUMENT,
    STORAGE_UNAVAILABLE,
    AUTHENTICATION_FAILED
}
